### ISSUE TITLE
`retryWith` with `Retry` behavior have to be defaulted to `Long.MAX_VALUE`

### ISSUE THREAD

**Issue by apischan** [reactor/reactor-addons#149]
1) As I understand default `retry(Predicate)` function have default amount of retries `Long.MAX_VALUE`. But if to change default `retry(Predicate)` to `retryWith(Retry)` without specifying `retryMax(int)` - the number of retries will be 1 (which is differs from default `retry`).
2) Also there is default `retry` that's parameter is `long` but in `Retry` from addons amount of retries is `int` that is wrong as for me. The type should be the same.
3) and in addition to the 1st point. What is the difference between this 2 pieces of code:
`someFlux.retryWith(Retry.any(RuntimeException.class))`
and
`someFlux.retryWith(Retry.any(RuntimeException.class).retryOnce())`
and why this `retryOnce()` exists at all? And why there is no something like `retryInfinite()`?

P.S. The most important point is 1st.

**Comment by simonbasle** [comment]
1. indeed it would make sense to align the default `retry` of core and the equivalent builder configuration.
2. Keep in mind this is a builder for the `retryWhen` operator, which is different from the `retry` one. At the time the builder was introduced, the easiest way to keep track of retry attempt was _zipping_ with a `Flux.range`... which is `Integer` based. There might be a solution to that with the newly introduced `index()` operator that tags the elements in the sequence with a `Long` index, so that misalignment is fixable (also that would be a breaking change)
3. I think it points back to issue one and proves that the original thought process was probably started around the idea of "illimited retries" per default. `retryOnce` make a ton more sense in that context, as a `retryMax(1)` alias that reads more nicely in the fluent API style.

**Comment by simonbasle** [comment]
Note: this is also true of `Repeat`.

**Comment by simonbasle** [comment]
Some occurrences of `Integer.MAX_VALUE` still to be fixed, and the previous PR didn't change the default number of retries from 1 to unlimited.
