### ISSUE TITLE
Implementation and javadoc of DefaultRetry differs

### ISSUE THREAD

**Issue by apischan** [reactor/reactor-addons#150]
Here is the code of `DefaultRetry#timeout` function.
```
@Override
public Retry<T> timeout(Duration timeout) {
    if (timeout.isNegative())
        throw new IllegalArgumentException("timeout should be >= 0");
    return new DefaultRetry<>(retryPredicate, Integer.MAX_VALUE, timeout,
            backoff, jitter, backoffScheduler, onRetry, applicationContext);
}
```
as I see here `maxIterations` argument sets to value `Integer.MAX_VALUE` but javadoc say
`All other properties of this retry function are retained in the returned instance.`

**Comment by apischan** [comment]
Also it is a bit strange that on each similar function to `timeout` new object has created. I saw why that happened and now I don't understand why this all fields in `AbstractRetry` are `final`...

**Comment by simonbasle** [comment]
since the object is used as both a kind of builder AND the actual retry Function passed to retryWhen, it was made immutable and each method call returns a new instance. that way you can configure a basic retry function that you can reuse in most of your code then fine tune it for a few specific use cases without impacting the other retries.

**Comment by Kindrat** [comment]
That's a strange approach leading to a generation of multiple objects per single flux/mono chain. Most use cases are - calling factory method and some methods to fine-tune default behavior. But when you are expecting to modify single property of retry object - method call will return new retry object. This leads to the error described above - when someone forgets to modify one of the methods it's getting inconsistent behavior. On the other hand - if only one field would be updated - there won't be any side-effects.

Maybe there are some use cases when you need a static template for all retry functions, but it would be more straightforward to have some method - e.g. `copy()` to explicitly create object copy.

**Comment by simonbasle** [comment]
For that style of builder, I think this is still the most sensible approach, however stranger it may look to you. Immutability is a safety belt that is important to have if we want to avoid a `build()` method at the end.

Compare the `Some variable = new SomeBuilder().foo().bar().build()` style: it is more interesting for more advanced cases where you have illegal combinations and you want the builder API to guide you in avoiding these. In this case you can mutate builder's internal state, because what the `build()` method does is use the final form of this state to create an instance _of a different type_, so you don't risk using the builder in two places and mistakenly mutate it in the middle.

The `Retry` pattern is more of a fluent multi-step factory method style. At each step, there is not really any "bad combination", it's just that there are a lot of potential fine tuning. But each step is a valid instance of the produced type (the retry `Function`), and as a result, it is too easy to use it (as a `Function`) in multiple places. Having mutability would lead to hidden side effects in these cases, which is problematic. Having immutability has no drawback. So, immutability.

**What @apischan noticed is definitely a bug though.** This method should reuse the current's `maxIterations`.

**Comment by simonbasle** [comment]
Actually I think this was done a bit on purpose: the `timeout` method is intended as "I want to keep retrying until the timeout expires", so with a default maxRetryAttempts of 1 this doesn't fit, hence the value change. It should be at least documented, and this can be actually changed in 3.2.0 at the same time as #149 (changing the retry attempt default to `Long.MAX_VALUE`, we then could let the timeout keep same maxRetry, and still open the door to a "timeout + maxRetry N" usage).

Will mark for 3.2.0.RELEASE.

**Comment by simonbasle** [comment]
Note: this is also true of `Repeat`.
