### ISSUE TITLE
Documentation of CacheFlux backed with a map

### ISSUE THREAD

**Issue by msoub** [reactor/reactor-addons#201]
Here is the doc of CacheFlux with the map endpoints:
```
      String key = "myCategory";
      LoadingCache<String, Object> graphs = Caffeine
          .newBuilder()
          .maximumSize(10_000)
          .expireAfterWrite(5, TimeUnit.MINUTES)
          .refreshAfterWrite(1, TimeUnit.MINUTES)
          .build(key -> createExpensiveGraph(key));
  
      Flux<Integer> cachedMyCategory = CacheFlux
          .lookup(graphs.asMap(), key, Integer.class)
          .onCacheMissResume(repository.findAllByCategory(key));
```

I think the `build(key -> createExpensiveGraph(key))` should be more explicit about the `Signal` abstraction. Indeed, one has to return a list of `Signal` in `createExpensiveGraph` for the load/refresh to work.

**Comment by wer-mathurin** [comment]
Using the cache manager seems to works as well.
var map = (Map) cacheManager.getCache("cache_name").getNativeCache();

Flux<Integer> cachedMyCategory = CacheFlux
          .lookup(map , key, Integer.class)
          .onCacheMissResume(repository.findAllByCategory(key));

I'm wondering if we can use the AsyncLoadingCache functionality of caffeine in conjunction with FluxCache? Since we want a full non blocking caching strategy.

It does not make sense to execute  repository.findAllByCategory(key) multiple time before it return something to the cache if multiple thread is call the "cache" at the same time.

Using Caffeine will likely respond to this use cases where it can return a CompletableFuture.  But the cache (AsyncLoadingCache) is a kind of map(but not a Map :-( )...so do not comply with the map EntryPoint.  Since I'm not an expert playing with Flux and Caching....It can be cool as well to document this use case.

**Comment by ben-manes** [comment]
`AsyncCache` was introduced in 2.7, which `AsyncLoadingCache`, and added the `asMap()` view. That is a `Map<K, CompletableFuture<V>>` view of the cache. A map is not self-loading, e.g. `Map.get` => `AsyncCache.getIfPresent`, but you can use `computeIfAbsent`.

I am not familiar with `CacheFlux`, but if it performs `onCacheMissResume` outside of the cache then it is racy. That could be done safely inside a `computeIfAbsent`, though. An easy way to adapt without using `CacheFlux` is to convert a `Flux` and `CompletableFuture` in the load method, and vice-versa when returning the results of cache.get. The blocking would only be the map write operation to create the future, while executing it would be non-blocking.

**Comment by wer-mathurin** [comment]
In the source of CacheFlux they store a Signal in the value of the map...so from my understanding this is not  what an AsyncCache is looking for :-)
.......
if (fromCache == null) {
		return otherSupplier.get()
				.materialize()
				 .collectList()
				.doOnNext(signals -> cacheMap.put(key, signals))
				 .flatMapIterable(Function.identity())
				.dematerialize();

So this is the same thing when they get the value form the cache, they are looking for a Signal.
I think this can be a good thing to mention that in the documentation.  But I also thing we can give an example of how to use the Async Caffeine with the Generic cache entry points of the FluxCache.  I will give it a try and post my findings.

**Comment by ben-manes** [comment]
I haven't had a good opportunity to use Reactor, though I've been wanting to find one. The approach that I was thinking is below. Its how I would naively integrate the two libraries, but isn't generic for other caching providers.

```java
AsyncLoadingCache<Key, Graph> graphs = Caffeine.newBuilder()
    .maximumSize(10_000)
    .build(new AsyncCacheLoader<Key, Graph>() {
      public Graph asyncLoad(Key key, Executoor executor) {
        Mono result = repository.getById(key);
        return result.toFuture();
      }
      public CompletableFuture<Map<Key, Graph>> asyncLoadAll(
        Iterable<Key> keys, Executor executor) {
          Flux<Graph> flux = repository.findAllByIds(keys);
          Mono<Map<Key, Graph>> mono = flux.collectMap(Graph::getKey);
          return mono.toFuture();
        }
    });

private Mono<Graph> getGraph(Key key) {
  CompletableFuture<Graph> future = graphs.get(key);
  return Mono.fromFuture(future);
}

private Flux<Graph> getGraphs(List<Key> keys) {
  CompletableFuture<Map<Key, Graph>> futures = graphs.getAll(key);
  return // some simple conversion code that I don't know offhand
}
```

**Comment by Toomy** [comment]
Hi Simon
With your last comment, do you mean that the CacheFlux / Cache should not be used for new projects anymore? I'm about to use it as it exactly fits my needs. Is there an alternative aproach that works like 'intercepting a flux flow to return an cached value instead of a new one' ?

Regards Markus

**Comment by simonbasle** [comment]
@Toomy I'd recommend against it if you can avoid it, as discussed in #237 it is not a bulletproof solution. For very simple in memory use cases, look into core operators like `Flux.cache(int)` and `Mono.cache(...)` (although I suspect if you ended up here these don't fit your bill).

**Comment by simonbasle** [comment]
superseded by #237
