### ISSUE TITLE
EOL reactor-logback in 3.3+

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-addons#204]

**Comment by smaldini** [comment]
Fixed by https://github.com/reactor/reactor-addons/commit/d3e5029c369576dc9245a1883e7df4afc4b4e775

**Comment by zaomianbao** [comment]
> Fixed by [d3e5029](https://github.com/reactor/reactor-addons/commit/d3e5029c369576dc9245a1883e7df4afc4b4e775)

@simonbasle Can you tell me the reason for removing reactor-logback?

**Comment by OlegDokuka** [comment]
The alternative is the usage of https://github.com/logfellow/logstash-logback-encoder which is a more performant alternative to that. 

Logback appended seems to be a legacy thing coming from reactor 2.x. Apart, this appended which was based on reactive-streams spec was not a good fit into the paradigm since reactive streams assume a controlled stream of events while logging is more of an uncontrolled one. Also, worth to mention that starting from 3.4.x all Unsafe based processors were removed from the API surface ( TopicProcessor was used underneath there) although deprecation happened in the 3.3 line as far as I remember (@simonbasle can correct me if I'm wrong)
