### ISSUE TITLE
RxJava 3 Adapter support

### ISSUE THREAD

**Issue by linux-china** [reactor/reactor-addons#224]
RxJava 3.0.0  has been released.    https://github.com/ReactiveX/RxJava/releases/tag/v3.0.0    Any plan to add RxJava2 Adapter support?   

From. "What's different in 3.0" https://github.com/ReactiveX/RxJava/wiki/What's-different-in-3.0, and I think just some package names changing.

**Comment by simonbasle** [comment]
Indeed, we should add adapters support. We can add RxJava3 as an optional dependency.

The question is, do we still need to have converters in both directions, or do we only need RxJava3-to-Reactor converters? (since RxJava3 also has a Reactive-Streams-to-RxJava3 interoperability).

@akarnokd any opinion ? (and congrats on the release! 🎉)

**Comment by akarnokd** [comment]
For efficiency, it is still advised to bridge back and forth via `FlowableSubscriber` and `CoreSubscriber` so that the workaround for the spec limitation regarding bad request don't add unnecessary overhead between the two.
