### ISSUE TITLE
ListenableFuture to Mono/Flux adapter

### ISSUE THREAD

**Issue by jansyk13** [reactor/reactor-addons#41]
When trying to use reactor in our Spring based project, I had to transform from `ListenableFuture` to `CompletableFuture` to leverage async part of Reactor. It would be handy to have some sort of adapter. Any plans for this?

Tried to put together an [example](https://github.com/jansyk13/reactor-addons/commit/f272c106c8a32bf6462277ca900f0c321d4c34f9).

**Comment by simonbasle** [comment]
@rstoyanchev we think that this should probably go into Spring 5 rather than on Reactor side, wdyt?

@jansyk13 in the meantime if you want to go from ListenableFuture to `Mono` in Spring 4 then converting to `CompletableFuture` is probably the best bet, or directly using `Mono.create`...

**Comment by rstoyanchev** [comment]
Yes this would belong in the Spring Framework especially with Spring 5 using Reactor as a core dependency for the reactive support.

Note in the Spring Framework we've had since 4.2 a `CompletableToListenableFutureAdapter` so you can wrap the following in a convenient utility method:
````java
Mono.fromFuture(new CompletableToListenableFutureAdapter(listenableFuture));
````

I'm wondering also what you are using that returns ListenableFuture? For example in Spring 5 we have a `WebClient ` that returns Mono and Flux as the core type. That will be an alternative to the RestTempate that you can already try out.

**Comment by kevinten10** [comment]
How about `Guava`'s [ListenableFuture ](https://github.com/google/guava/blob/master/guava/src/com/google/common/util/concurrent/ListenableFuture.java) adapter?
